# Generated by Django 5.0.14 on 2026-06-09 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrier_code', models.CharField(db_index=True, max_length=30)),
                ('tracking_number', models.CharField(db_index=True, max_length=100)),
                ('region', models.CharField(choices=[('kr', '한국'), ('jp', '일본'), ('intl', '국제')], default='kr', max_length=10)),
                ('result', models.JSONField()),
                ('fetched_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-fetched_at'],
                'unique_together': {('carrier_code', 'tracking_number')},
            },
        ),
    ]
