# Generated by Django 5.0.14 on 2026-06-09 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KoreanMall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('domain', models.CharField(max_length=255)),
                ('logo_url', models.URLField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MallCrawlJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_url', models.URLField(max_length=2048)),
                ('category_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', '대기'), ('processing', '크롤중'), ('completed', '완료'), ('failed', '실패')], db_index=True, default='pending', max_length=20)),
                ('products_count', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('last_crawled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crawl_jobs', to='malls.koreanmall')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
