# Generated by Django 5.0.14 on 2026-06-09 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(help_text='Product.category 값과 일치해야 함', max_length=100)),
                ('display_title', models.CharField(blank=True, default='', help_text='비워두면 category_name 사용', max_length=100)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_categories', to='malls.koreanmall')),
            ],
            options={
                'ordering': ['display_order', 'mall__name', 'category_name'],
                'unique_together': {('mall', 'category_name')},
            },
        ),
    ]
