# Generated by Django 5.0.14 on 2026-06-01 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='키')),
                ('value', models.CharField(max_length=500, verbose_name='값')),
                ('group', models.CharField(choices=[('pricing', '구매대행 가격 정책'), ('shipping', '배송비 상수'), ('tariff', '관세 설정'), ('exchange', '환율 설정')], db_index=True, default='pricing', max_length=20, verbose_name='그룹')),
                ('description', models.TextField(blank=True, default='', verbose_name='설명')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '설정값',
                'verbose_name_plural': '설정값',
                'ordering': ['group', 'key'],
            },
        ),
    ]
