# Generated by Django 5.0.14 on 2026-06-22 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_shippingtracking_dhub_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingtracking',
            name='current_stage',
            field=models.CharField(choices=[('shipment_sent', '상품발송'), ('intl_transit', '국제운송'), ('customs', '통관'), ('domestic_delivery', '국내배송'), ('delivered', '배송완료')], db_index=True, default='shipment_sent', max_length=20, verbose_name='현재 단계'),
        ),
        migrations.AddField(
            model_name='shippingtracking',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='배송완료 시각'),
        ),
        migrations.AddField(
            model_name='shippingtracking',
            name='delivery_region',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='배송 지역'),
        ),
        migrations.CreateModel(
            name='TrackingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(db_index=True, max_length=50)),
                ('occurred_at', models.DateTimeField(db_index=True, verbose_name='발생 시각')),
                ('stage', models.CharField(choices=[('shipment_sent', '상품발송'), ('intl_transit', '국제운송'), ('customs', '통관'), ('domestic_delivery', '국내배송'), ('delivered', '배송완료')], db_index=True, max_length=20, verbose_name='단계')),
                ('description', models.CharField(max_length=500, verbose_name='이벤트 내용')),
                ('location', models.CharField(blank=True, default='', max_length=255, verbose_name='위치')),
                ('source', models.CharField(choices=[('seller', '판매자'), ('intl', '국제운송사'), ('customs', '세관'), ('carrier', '국내 택배사'), ('system', '시스템')], default='carrier', max_length=20, verbose_name='출처')),
                ('raw_code', models.CharField(blank=True, default='', max_length=50, verbose_name='원천 상태코드')),
                ('raw', models.JSONField(blank=True, null=True, verbose_name='원천 데이터')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '배송 추적 이벤트',
                'verbose_name_plural': '배송 추적 이벤트',
                'ordering': ['occurred_at', 'id'],
                'indexes': [models.Index(fields=['order_number', 'occurred_at'], name='logistics_t_order_n_c15b27_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='trackingevent',
            constraint=models.UniqueConstraint(fields=('order_number', 'occurred_at', 'description'), name='uniq_tracking_event'),
        ),
    ]
