# Generated by Django 5.0.14 on 2026-06-28 14:03

from django.db import migrations, models


def remap_customs_stage(apps, schema_editor):
    """제거된 'customs' 단계 → 'intl_transit' 로 보수적 remap (현지배송으로 과진행 방지)."""
    ShippingTracking = apps.get_model('logistics', 'ShippingTracking')
    TrackingEvent = apps.get_model('logistics', 'TrackingEvent')
    ShippingTracking.objects.filter(current_stage='customs').update(current_stage='intl_transit')
    TrackingEvent.objects.filter(stage='customs').update(stage='intl_transit')


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0003_shippingtracking_current_stage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingtracking',
            name='current_stage',
            field=models.CharField(choices=[('shipment_sent', '상품발송'), ('intl_transit', '국제운송'), ('domestic_delivery', '현지배송'), ('delivered', '배송완료')], db_index=True, default='shipment_sent', max_length=20, verbose_name='현재 단계'),
        ),
        migrations.AlterField(
            model_name='trackingevent',
            name='stage',
            field=models.CharField(choices=[('shipment_sent', '상품발송'), ('intl_transit', '국제운송'), ('domestic_delivery', '현지배송'), ('delivered', '배송완료')], db_index=True, max_length=20, verbose_name='단계'),
        ),
        migrations.RunPython(remap_customs_stage, migrations.RunPython.noop),
    ]
