# Generated by Django 5.0.14 on 2026-06-28 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0004_alter_shippingtracking_current_stage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomsClearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('customs_type', models.CharField(blank=True, choices=[('list', '목록통관'), ('general', '일반통관')], max_length=10, verbose_name='통관 종류')),
                ('result', models.CharField(choices=[('pending', '통관 대기'), ('cleared', '통관 완료'), ('rejected', '통관 거절'), ('returned', '반송')], db_index=True, default='pending', max_length=10, verbose_name='통관 결과')),
                ('reject_reason', models.TextField(blank=True, verbose_name='거절 사유')),
                ('partial_refund_amount', models.FloatField(blank=True, null=True, verbose_name='해당 상품 부분환불 예정액')),
                ('notified_at', models.DateTimeField(blank=True, null=True, verbose_name='고객 안내(CS 발송) 시각')),
                ('response_deadline', models.DateTimeField(blank=True, null=True, verbose_name='고객 응답 기한')),
                ('customer_responded_at', models.DateTimeField(blank=True, null=True, verbose_name='고객 응답 시각 (null=미응답)')),
                ('refund_processed_at', models.DateTimeField(blank=True, null=True, verbose_name='부분환불 실행 시각')),
                ('refund_amount', models.FloatField(blank=True, null=True, verbose_name='실제 환불액')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
