# Generated by Django 5.0.14 on 2026-06-28 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0005_customsclearance'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryFailure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('failure_reason', models.CharField(choices=[('address_error', '주소 오류'), ('absence', '부재'), ('refusal', '수취 거부'), ('damaged', '파손'), ('other', '기타')], default='address_error', max_length=20, verbose_name='실패 사유')),
                ('responsible', models.CharField(choices=[('customer', '고객'), ('carrier', '배송사'), ('dk', 'DK(당사)')], default='customer', max_length=10, verbose_name='귀책')),
                ('cost_burden', models.CharField(choices=[('customer', '고객'), ('carrier', '배송사'), ('dk', 'DK(당사)')], default='customer', max_length=10, verbose_name='재배송/반송비 부담')),
                ('status', models.CharField(choices=[('stored', '보관 중'), ('reship', '재배송'), ('returned', '반품'), ('disposed', '폐기')], db_index=True, default='stored', max_length=10, verbose_name='처리 상태')),
                ('item_value', models.FloatField(blank=True, null=True, verbose_name='상품 가액 (처분 분기용)')),
                ('notified_at', models.DateTimeField(blank=True, null=True, verbose_name='고객 안내(CS 발송) 시각')),
                ('storage_deadline', models.DateTimeField(blank=True, null=True, verbose_name='보관 기한')),
                ('customer_responded_at', models.DateTimeField(blank=True, null=True, verbose_name='고객 응답 시각 (null=미응답)')),
                ('disposition', models.CharField(blank=True, choices=[('dispose', '폐기'), ('return', '반품')], max_length=10, verbose_name='처분 (폐기/반품)')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='처리 완료 시각')),
                ('memo', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
