# Generated by Django 5.0.14 on 2026-06-01 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_currency', models.CharField(default='JPY', max_length=5)),
                ('target_currency', models.CharField(default='KRW', max_length=5)),
                ('rate', models.FloatField()),
                ('source', models.CharField(blank=True, default='', max_length=100)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fetched_at'],
            },
        ),
        migrations.CreateModel(
            name='PricingQuoteLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_price', models.FloatField(blank=True, null=True)),
                ('discounted_price', models.FloatField(blank=True, null=True)),
                ('currency', models.CharField(default='KRW', max_length=5)),
                ('krw_per_jpy_market', models.FloatField()),
                ('result', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
