# Generated by Django 5.0.14 on 2026-06-09 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='brand',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
