# Generated by Django 5.0.14 on 2026-06-01 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TariffLookupLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=500)),
                ('result', models.JSONField(default=dict)),
                ('rate', models.FloatField(blank=True, null=True)),
                ('duty_type', models.CharField(blank=True, default='', max_length=20)),
                ('matched_item', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
