# Generated by Django 5.0.14 on 2026-06-22 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_product_is_prima'),
        ('tariff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductHsClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_suggested', models.JSONField(blank=True, default=dict, help_text='{hs_code, matched_item, full_path, depth_path, rate, reason, ...}', verbose_name='AI 추천')),
                ('ai_alternatives', models.JSONField(blank=True, default=list, help_text='채택 여지가 있는 다른 분류 후보 목록', verbose_name='AI 대안 후보')),
                ('ai_search_expansion', models.CharField(blank=True, default='', max_length=500, verbose_name='AI 검색 확장어')),
                ('final_hs_code', models.CharField(blank=True, db_index=True, default='', max_length=30, verbose_name='확정 HS코드(순번)')),
                ('final_category', models.CharField(blank=True, default='', max_length=500, verbose_name='확정 통관 카테고리(품명)')),
                ('final_full_path', models.TextField(blank=True, default='', verbose_name='확정 분류 경로')),
                ('status', models.CharField(choices=[('pending', '확인 대기'), ('confirmed', '확정')], db_index=True, default='pending', max_length=12, verbose_name='상태')),
                ('decision_source', models.CharField(blank=True, choices=[('ai_confirmed', 'AI 추천 그대로 확정'), ('alternative', '대안 후보 선택'), ('manual', '직접 입력 수정')], default='', max_length=15, verbose_name='확정 방식')),
                ('inspector', models.CharField(blank=True, default='', max_length=100, verbose_name='검수 담당자')),
                ('inspector_note', models.TextField(blank=True, default='', verbose_name='검수 피드백/메모')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='확정 시각')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hs_classification', to='products.product', verbose_name='상품')),
            ],
            options={
                'verbose_name': '상품 HS 분류',
                'verbose_name_plural': '상품 HS 분류',
                'ordering': ['-updated_at'],
            },
        ),
    ]
