# Generated by Django 5.0.14 on 2026-06-09 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_product_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='pgtransaction',
            name='amount_jpy',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pgtransaction',
            name='gmo_access_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='pgtransaction',
            name='gmo_access_pass',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='pgtransaction',
            name='gmo_approve',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='pgtransaction',
            name='gmo_forward',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='pgtransaction',
            name='gmo_job_cd',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='pgtransaction',
            name='gmo_order_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='pgtransaction',
            name='pg_transaction_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
    ]
