# Generated by Django 5.0.14 on 2026-06-19 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_pgtransaction_amount_jpy_pgtransaction_gmo_access_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pgtransaction',
            name='currency',
            field=models.CharField(default='JPY', max_length=3),
        ),
        migrations.AddField(
            model_name='pgtransaction',
            name='provider',
            field=models.CharField(choices=[('gmo', 'GMO Payment Gateway'), ('gmo_paypay', 'GMO PayPay'), ('stripe', 'Stripe'), ('adyen', 'Adyen')], default='gmo', max_length=20),
        ),
        migrations.AddField(
            model_name='pgtransaction',
            name='provider_order_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
    ]
