# Generated by Django 5.0.14 on 2026-06-19 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_pgtransaction_currency_pgtransaction_provider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsnapshot',
            name='product_name_en',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
