# Generated by Django 5.0.14 on 2026-06-20 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_productsnapshot_product_name_en'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('purchase_account', models.CharField(blank=True, max_length=255)),
                ('collection_address', models.TextField(blank=True)),
                ('actual_price', models.FloatField(blank=True, null=True)),
                ('domestic_shipping_fee', models.FloatField(default=0)),
                ('currency', models.CharField(default='KRW', max_length=10)),
                ('cs_user', models.CharField(blank=True, db_index=True, max_length=255)),
                ('memo', models.TextField(blank=True)),
                ('purchased_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
