# Generated by Django 5.0.14 on 2026-06-09 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(blank=True, db_index=True, max_length=50)),
                ('customer_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('purpose', models.CharField(choices=[('inspection', '검수 사진'), ('product', '상품 이미지'), ('receipt', '영수증'), ('other', '기타')], default='other', max_length=20)),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('s3_key', models.CharField(max_length=1024)),
                ('public_url', models.URLField(max_length=2048)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['order_number', 'purpose'], name='storage_upl_order_n_76308f_idx')],
            },
        ),
    ]
