# Generated by Django 5.0.14 on 2026-06-08 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs', '0002_inquiry_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='inquiry_type',
            field=models.CharField(choices=[('general', '일반 문의'), ('cancel', '취소 문의'), ('refund', '환불 문의'), ('exchange', '교환 문의'), ('return', '반품 문의'), ('shipping', '배송 문의'), ('shipping_delay', '배송 지연'), ('price_error', '가격 오차'), ('other', '기타')], db_index=True, default='general', max_length=20),
        ),
    ]
