# Generated by Django 5.0.14 on 2026-06-28 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs', '0004_alter_inquiry_inquiry_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancelrequest',
            name='reason_type',
            field=models.CharField(choices=[('change_of_mind', '단순변심'), ('defect', '하자/불량'), ('mis_ship', '오배송'), ('inspection', '검수이슈'), ('other', '기타')], db_index=True, default='change_of_mind', max_length=20),
        ),
        migrations.AddField(
            model_name='refundrequest',
            name='reason_type',
            field=models.CharField(choices=[('change_of_mind', '단순변심'), ('defect', '하자/불량'), ('mis_ship', '오배송'), ('inspection', '검수이슈'), ('other', '기타')], db_index=True, default='change_of_mind', max_length=20),
        ),
    ]
