# Generated by Django 5.0.14 on 2026-06-01 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingRateTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_key', models.CharField(choices=[('KSE_SEA_STANDARD', 'KSE 해상 Standard (JPY)'), ('KSE_SEA_LIGHT', 'KSE 해상 Light (JPY)'), ('KSE_AIR_STANDARD', 'KSE 항공 Standard (JPY)'), ('KSE_AIR_LIGHT', 'KSE 항공 Light (JPY)'), ('KSE_SDEX_STANDARD', 'KSE SDEX Standard (JPY)'), ('KSE_SDEX_LIGHT', 'KSE SDEX Light (JPY)'), ('CJL_DOOR_TO_DOOR', 'CJL Door to Door (KRW)')], max_length=30, unique=True, verbose_name='요율표 종류')),
                ('currency', models.CharField(default='JPY', max_length=5, verbose_name='통화')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('note', models.TextField(blank=True, default='', verbose_name='비고')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '배송 요율표',
                'verbose_name_plural': '배송 요율표',
                'ordering': ['table_key'],
            },
        ),
        migrations.CreateModel(
            name='ShippingRateEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_break_kg', models.FloatField(verbose_name='구간 무게 (kg)')),
                ('freight', models.IntegerField(verbose_name='운임')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='shipping.shippingratetable')),
            ],
            options={
                'verbose_name': '요율 구간',
                'verbose_name_plural': '요율 구간',
                'ordering': ['weight_break_kg'],
                'unique_together': {('table', 'weight_break_kg')},
            },
        ),
    ]
