# Generated by Django 5.0.14 on 2026-06-19 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0002_shippingratetable_shippingrateentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingratetable',
            name='table_key',
            field=models.CharField(choices=[('KSE_SEA_STANDARD', 'KSE 해상 Standard (JPY)'), ('KSE_SEA_LIGHT', 'KSE 해상 Light (JPY)'), ('KSE_AIR_STANDARD', 'KSE 항공 Standard (JPY)'), ('KSE_AIR_LIGHT', 'KSE 항공 Light (JPY)'), ('KSE_SDEX_STANDARD', 'KSE SDEX Standard (JPY)'), ('KSE_SDEX_LIGHT', 'KSE SDEX Light (JPY)'), ('CJL_DOOR_TO_DOOR', 'CJL Door to Door (KRW)'), ('FB_AIR_STANDARD', 'FastBox 항공 Standard (KRW)'), ('FB_AIR_VIP', 'FastBox 항공 VIP — 월 1,000건+ (KRW)'), ('FB_AIR_SVIP', 'FastBox 항공 SVIP — 월 3,000건+ (KRW)'), ('FB_AIR_SSVIP', 'FastBox 항공 SSVIP — 월 7,000건+ (KRW)')], max_length=30, unique=True, verbose_name='요율표 종류'),
        ),
    ]
