# Generated by Django 5.0.14 on 2026-06-19 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0003_alter_shippingratetable_table_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryWeightPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100, unique=True, verbose_name='카테고리명')),
                ('avg_weight_kg', models.FloatField(verbose_name='평균 무게 (kg)')),
                ('note', models.TextField(blank=True, verbose_name='비고')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '카테고리 평균 무게',
                'verbose_name_plural': '카테고리 평균 무게',
                'ordering': ['category_name'],
            },
        ),
        migrations.CreateModel(
            name='ShippingCarrierProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='프로필명')),
                ('carrier_code', models.CharField(choices=[('FB', 'FastBox (DHUB)'), ('KSE', 'KSE'), ('CJL', 'CJL Door to Door'), ('EMS', '한국우편 EMS')], max_length=10, verbose_name='배송사')),
                ('mode', models.CharField(choices=[('AIR', '항공'), ('SEA', '해운'), ('EMS', 'EMS')], max_length=10, verbose_name='운송 방식')),
                ('fb_tier', models.CharField(blank=True, choices=[('STANDARD', '표준'), ('VIP', 'VIP (월 1,000건+)'), ('SVIP', 'SVIP (월 3,000건+)'), ('SSVIP', 'SSVIP (월 7,000건+)')], default='STANDARD', help_text='carrier_code=FB 일 때만 사용', max_length=10, verbose_name='FB 등급')),
                ('fb_tax_mode', models.CharField(blank=True, choices=[('DDU', 'DDU — 구매자 납부'), ('DDP', 'DDP — 판매자 납부')], default='DDU', help_text='carrier_code=FB 일 때만 사용', max_length=5, verbose_name='FB 세금 납부')),
                ('is_default', models.BooleanField(default=False, help_text='같은 mode 내에서 기본으로 사용할 배송사를 지정', verbose_name='기본 배송사')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('sort_order', models.IntegerField(default=0, verbose_name='정렬 순서')),
                ('note', models.TextField(blank=True, verbose_name='비고')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '배송사 프로필',
                'verbose_name_plural': '배송사 프로필',
                'ordering': ['sort_order', 'carrier_code'],
            },
        ),
        migrations.AlterField(
            model_name='shippingratetable',
            name='table_key',
            field=models.CharField(choices=[('KSE_SEA_STANDARD', 'KSE 해상 Standard (JPY)'), ('KSE_SEA_LIGHT', 'KSE 해상 Light (JPY)'), ('KSE_AIR_STANDARD', 'KSE 항공 Standard (JPY)'), ('KSE_AIR_LIGHT', 'KSE 항공 Light (JPY)'), ('KSE_SDEX_STANDARD', 'KSE SDEX Standard (JPY)'), ('KSE_SDEX_LIGHT', 'KSE SDEX Light (JPY)'), ('CJL_DOOR_TO_DOOR', 'CJL Door to Door (KRW)'), ('FB_AIR_STANDARD', 'FastBox 항공 Standard (KRW)'), ('FB_AIR_VIP', 'FastBox 항공 VIP — 월 1,000건+ (KRW)'), ('FB_AIR_SVIP', 'FastBox 항공 SVIP — 월 3,000건+ (KRW)'), ('FB_AIR_SSVIP', 'FastBox 항공 SSVIP — 월 7,000건+ (KRW)'), ('EMS_JP_STANDARD', '한국우편 EMS → 일본 Standard (KRW)')], max_length=30, unique=True, verbose_name='요율표 종류'),
        ),
    ]
