# Generated by Django 5.0.14 on 2026-06-09 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(db_index=True, max_length=255)),
                ('provider', models.CharField(choices=[('line', 'LINE')], max_length=20)),
                ('provider_uid', models.CharField(max_length=255)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('picture_url', models.URLField(blank=True, max_length=1024)),
                ('access_token', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['customer_id', 'provider'], name='auth_social_custome_0ca117_idx')],
                'unique_together': {('provider', 'provider_uid')},
            },
        ),
    ]
