# Generated by Django 5.0.14 on 2026-06-09 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_lang', models.CharField(default='KO', max_length=10)),
                ('target_lang', models.CharField(default='JA', max_length=10)),
                ('source_text', models.TextField()),
                ('translated_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['source_lang', 'target_lang', 'source_text'], name='translate_t_source__78a592_idx')],
            },
        ),
    ]
