# Generated by Django 5.0.14 on 2026-06-01 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraperequest',
            name='domain',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='scraperequest',
            name='page_type',
            field=models.CharField(choices=[('auto', 'Auto'), ('list', 'List'), ('detail', 'Detail')], default='auto', max_length=10),
        ),
        migrations.AddField(
            model_name='scraperesult',
            name='items_count',
            field=models.IntegerField(default=0),
        ),
    ]
