# Generated by Django 5.0.14 on 2026-06-01 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0002_scraperequest_domain_scraperequest_page_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraperequest',
            name='category',
            field=models.CharField(choices=[('shopping', '쇼핑'), ('news', '뉴스/블로그'), ('real_estate', '부동산'), ('jobs', '채용/구인'), ('general', '일반')], db_index=True, default='shopping', max_length=20),
        ),
    ]
