# Generated by Django 5.0.14 on 2026-06-09 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0003_scraperequest_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrlVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(db_index=True, max_length=255)),
                ('url', models.URLField(max_length=2048)),
                ('title', models.CharField(blank=True, default='', max_length=1024)),
                ('visited_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-visited_at'],
                'indexes': [models.Index(fields=['customer_id', '-visited_at'], name='scraping_ur_custome_8539f8_idx')],
            },
        ),
    ]
