# Generated by Django 5.0.14 on 2026-06-19 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='country',
            field=models.CharField(default='JP', max_length=2),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='name_en',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='name_kana',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
