# Generated by Django 5.0.14 on 2026-06-09 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(db_index=True, max_length=255)),
                ('channel', models.CharField(choices=[('line', 'LINE'), ('email', 'Email'), ('sms', 'SMS')], max_length=10)),
                ('event', models.CharField(choices=[('order_confirmed', '주문 확인'), ('payment_complete', '결제 완료'), ('purchase_started', '구매 시작'), ('inspection_done', '검수 완료'), ('shipping_kr', '한국 발송'), ('shipping_intl', '국제 배송 중'), ('shipping_jp', '일본 배송 중'), ('delivered', '배송 완료'), ('cancel_complete', '취소 완료'), ('refund_complete', '환불 완료'), ('custom', '커스텀')], max_length=30)),
                ('recipient', models.CharField(max_length=255)),
                ('order_number', models.CharField(blank=True, db_index=True, max_length=50)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField(blank=True)),
                ('send_status', models.CharField(choices=[('pending', '발송 대기'), ('sent', '발송 성공'), ('failed', '발송 실패')], default='pending', max_length=10)),
                ('error_detail', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['customer_id', 'channel', '-created_at'], name='notify_noti_custome_b63879_idx')],
            },
        ),
    ]
