# Generated by Django 5.0.14 on 2026-06-28 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationlog',
            name='event',
            field=models.CharField(choices=[('order_confirmed', '주문 확인'), ('payment_complete', '결제 완료'), ('purchase_started', '구매 시작'), ('inspection_done', '검수 완료'), ('shipping_kr', '한국 발송'), ('shipping_intl', '국제 배송 중'), ('shipping_jp', '일본 배송 중'), ('delivered', '배송 완료'), ('cancel_complete', '취소 완료'), ('refund_complete', '환불 완료'), ('customs_rejected', '통관 거절 안내'), ('custom', '커스텀')], max_length=30),
        ),
    ]
