# Generated by Django 5.0.14 on 2026-06-19 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_is_recommended_product_mall'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='arrival_status',
            field=models.CharField(choices=[('ordered', '주문완료'), ('in_transit', '배송중'), ('arrived', '도착'), ('inspected', '검수완료')], db_index=True, default='ordered', max_length=15, verbose_name='도착 상태'),
        ),
        migrations.AddField(
            model_name='product',
            name='arrived_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='도착 확인 시각'),
        ),
        migrations.AddField(
            model_name='product',
            name='inbound_courier',
            field=models.CharField(blank=True, default='', help_text='예: CJ대한통운, 우체국, 롯데택배', max_length=50, verbose_name='택배사'),
        ),
        migrations.AddField(
            model_name='product',
            name='inbound_note',
            field=models.TextField(blank=True, default='', verbose_name='입고 메모'),
        ),
        migrations.AddField(
            model_name='product',
            name='inbound_order_number',
            field=models.CharField(blank=True, db_index=True, default='', help_text='이메일 수신 후 입력', max_length=100, verbose_name='구매 오더번호'),
        ),
        migrations.AddField(
            model_name='product',
            name='inbound_tracking_number',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='송장번호'),
        ),
        migrations.AddField(
            model_name='product',
            name='inspected_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='검수 완료 시각'),
        ),
        migrations.AddField(
            model_name='product',
            name='inspection_required',
            field=models.BooleanField(default=False, help_text='사진 촬영·검수 서비스 신청 여부', verbose_name='검수 서비스'),
        ),
        migrations.CreateModel(
            name='ProductArrivalPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(upload_to='arrival_photos/%Y/%m/', verbose_name='도착 사진')),
                ('note', models.CharField(blank=True, default='', max_length=255, verbose_name='메모')),
                ('captured_at', models.DateTimeField(auto_now_add=True, verbose_name='촬영/업로드 시각')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrival_photos', to='products.product', verbose_name='상품')),
            ],
            options={
                'verbose_name': '도착 사진',
                'verbose_name_plural': '도착 사진',
                'ordering': ['-captured_at'],
            },
        ),
    ]
