# Generated by Django 5.0.14 on 2026-06-21 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_arrival_status_product_arrived_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_prima',
        ),
    ]
