# Generated by Django 5.0.14 on 2026-06-01 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape_template', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatebuildlog',
            name='domain',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='templatebuildlog',
            name='merged_from',
            field=models.TextField(blank=True, default=''),
        ),
    ]
