# Generated by Django 5.0.14 on 2026-06-01 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape_template', '0002_templatebuildlog_domain_templatebuildlog_merged_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatebuildlog',
            name='category',
            field=models.CharField(blank=True, db_index=True, default='shopping', max_length=20),
        ),
    ]
